# Workflow derived from https://github.com/Morrison-Lab/gha/blob/main/examples/check-non-standard-chars.yml
name: Check Non-Standard Characters

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  check:
    uses: Morrison-Lab/gha/.github/workflows/check-non-standard-chars.yml@v1
